services:
  aria:
    build:
      context: .
      dockerfile: Dockerfile
    image: steve0314/aria
    restart: always
    networks:
      - sillasol-net

networks:
  sillasol-net:
    external: true